
  [build]
    base= "/opt/build/repo/client"
    command= "npm run build"
    commandOrigin= "config"
    publish= "/opt/build/repo/client/dist"
    publishOrigin= "ui"
    
  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
